</sys/src/ape/config
OS=0568qv
all:
	$O^a $objtype/getfcr.s
	pcc -I../glkterm -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -c *.c
	pcc -I../glkterm -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -o cglulxe main.$O files.$O vm.$O exec.$O funcs.$O operand.$O string.$O glkop.$O heap.$O serial.$O search.$O accel.$O float.$O gestalt.$O osdepend.$O profile.$O unixstrt.$O getfcr.$O -lglkterm
install:
	mk
	cp cglulxe /$objtype/bin
clean:
	rm -f *.[$OS] [$OS].out y.tab.? lex.yy.c y.debug y.output $TARG $CLEANFILES
	rm glulxe
